Added downloading proper file extensions
vn-ki/anime-downloader pull request #496
Opened 2020-08-26 23:33 UTC by nate-moo

For example, if a video stream source is m3u8 intead of downloading the file as x.m3u8 and renaming it to {anime_title}/{anime_title}_{ep_no}.mp4, we download it as x.m3u8 and dont rename the extension so the extension will stay but the name will change to the configured value: {anime_title}/{anime_title}_{ep_no}.m3u8. (except for nyaa which I have set to always be mkv bc that is almost always the file ext used)

2020-08-26 23:44 UTC, IguanasInPyjamas approved these changes
This is fine, someone should do some testing first.

2020-08-27 00:17 UTC, nate-moo commented
> This is fine, someone should do some testing first.

tested, also found out alot of sites dont work lmao

gogoanime: works,

kisscartoon: got EOF from server?,

twist: works, 

animeflv: No supported Host on the 3 tested maybe broken?,

Itsaturday: nonetype error,

animefreak: Network error? maybe bc im using VPN 
(Edit: nope)

animeout: works, 

animixplay: works, 

animesimple: has other issues, 

ryuanime: has other issues, 

animerush: has issues with node sandboxing,

animeflix: resource not found?,

kickass: works,

Dreamanime: times out,

erai-raws: 403 forbidden?,

watchmovie: works,

animekisa: node sandbox issue,

animedaisuki: vidlink domain name not found,

animevibe: cloudflare?,

yify: fuck yify... it timed out,

animefree: http 400 bad request?

voiranime: node sandbox issue,

vidstream: works

2020-08-27 05:43 UTC, Blatzar commented
I'll do some tweaking to solve https://github.com/vn-ki/anime-downloader/issues/428 too.

2020-08-27 05:45 UTC, nate-moo commented
> I'll do some tweaking to solve #428 too.

you could essentially just not rename it when downloading from nyaa or a downloader specific site like animeout

2020-09-09 01:38 UTC, nate-moo commented
waka waka waka waka waka waka waka waka I'm pacman

2020-09-12 09:14 UTC, Blatzar requested changes

2020-09-12 09:14 UTC, Blatzar commented on anime_downloader/util.py
> +    file_name, file_ext = os.path.splitext(episode.source().stream_url)
Get the final redirect url with requests.get(episode.source().stream_url, stream=True)

2020-09-12 09:14 UTC, Blatzar commented on anime_downloader/util.py
> +    file_ext = file_ext.split('?', 1)[0]
Use urllib instead

2020-09-12 09:14 UTC, Blatzar commented on anime_downloader/util.py
> +    if file_ext == ".php" or file_ext == "" or file_ext == "html":
Use a dict/list instead of tons of or statements.

2020-09-12 09:14 UTC, Blatzar commented on anime_downloader/util.py
> +
No extra spaces

2020-10-15 00:12 UTC, IguanasInPyjamas commented
Closing in favor of #519

2020-10-15 00:12 UTC, closed without merging

2021-02-03 02:50 UTC, nate-moo commented
ah yes in favor of something that hasn't gone anywhere in a while 
*I also haven't done anything with this so it's partially my fault*